### ISSUE TITLE
Problem to connect to mongodb - RateLimiterMongo

### ISSUE THREAD

**Issue by gsmgg** [animir/node-rate-limiter-flexible#118]
Hi, I'm working on an open source project and node-rate-limiter-Flexible is a perfect library for the project.

As the project intends to deal with many connections and the budget for computational activity is low, I decided to connect the library through mongodb, in the free version (shared plan).

Well, my problem is that I can't connect the library with mongodb at all, it always results in this error:

```
[nodemon] starting ts-node ./src/index.ts

(node:1758) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use node --trace-warnings ... to show where the warning was created)

// The error
Error =>  Error: Mongo connection is not established
    at RateLimiterMongo._upsert (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/rate-limiter-flexible/lib/RateLimiterMongo.js:117:29)
    at /Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:203:12
    at new Promise (<anonymous>)
    at RateLimiterMongo.consume (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:195:12)
    at rateLimiterMiddleware (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/src/index.ts:50:6)
    at Layer.handle [as handle_request] (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/index.js:317:13)
    at /Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/index.js:275:10)
```

I wrote a simple code in ts (ready to use), just to demonstrate the problem:

```ts
// TypeScrip code
import express from "express";

import { RateLimiterMongo } from "rate-limiter-flexible";
import MongoClient from "mongodb";

const app = express();

const mongoOpts = {
  useNewUrlParser: true,
  reconnectTries: Number.MAX_VALUE,
  reconnectInterval: 100,
};

/**
 * I created this project in mongodb just to test this application, 
 * so I put the username and password here in the code just 
 * to make your testing simpler.
 * 
 * THIS IS NOT A PRODUCTION BD and will be disabled in the future 
 * when I manage to fix the problem.
 */

const db = {
  user: "test_admin",
  password: "Lc8vIC3WWXOBuMN9",
  dbname: "rate-limit",
};
const url = `mongodb+srv://${db.user}:${db.password}@testedb.bax1d.mongodb.net/${db.dbname}?retryWrites=true&w=majority`;

const mongoConn = MongoClient.connect(url, mongoOpts);

const opts = {
  storeClient: mongoConn,
  dbName: "rate-limit",
  points: 10, // 10 points
  duration: 60, // 60 seconds
};
const rateLimiterMiddleware = (
  req: express.Request,
  res: express.Response,
  next: express.NextFunction
) => {
  const userId = req.query.uid as string;

  if (!userId) {
    res.status(401).send("Unauthorized");
    return;
  }

  const rateLimiterMongo = new RateLimiterMongo(opts);
  rateLimiterMongo
    .consume(userId, 2) // consume 2 points
    .then((rateLimiterRes) => {
      console.log(`User ${userId} do a request`);
      next();
    })
    .catch((rateLimiterRes) => {
      console.log("Error => ", rateLimiterRes);
      res.status(429).send("Too Many Requests");
    });
};

app.use(rateLimiterMiddleware);

app.get("/", (req: express.Request, res: express.Response) => {
  res.send(`Hi user ${req.params.uid}!`);
});

const port = 3000;
app.listen(port, () => {
  console.log(`Server listening at http://localhost:${port}`);
});
```

If anyone can help me, I would be very grateful. Thanks.

**Comment by gustavo-simoes** [comment]
I tried it in several different ways, like middleware (as shown in the code), inside the HTTP handler, changing the URL following the [official documentation](https://docs.mongodb.com/manual/reference/connection-string/), but nothing worked :(

```js
// I tried using the url like that, but I always get the same error.
const url = `mongodb+srv://${db.user}:${db.password}@testedb.bax1d.mongodb.net/`;
```

**Comment by animir** [comment]
@gustavo-simoes Hi
I suggest two check two things:
1. try to make some query with `mongoConn` to check if it works
2. check MongoDB Driver warning with something about `useUnifiedTopology: true`

I hope, this helps

**Comment by gsmgg** [comment]
I tried making a query with mongoConn as suggested, and it worked well (Using the same url)!  Also change the mongo options to `useUnifiedTopology: true`, and this removes the warning log.

But, when I activate the route, and the library (RateLimiterMong) is called, it log the same problem: *"Error: Mongo connection is not established"*. I have no idea what to do anymore...

```
Server listening at http://localhost:3000
Error =>  Error: Mongo connection is not established
    at RateLimiterMongo._upsert (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/rate-limiter-flexible/lib/RateLimiterMongo.js:117:29)
    at /Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:203:12
    at new Promise (<anonymous>)
    at RateLimiterMongo.consume (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:195:12)
    at rateLimiterMiddleware (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/src/index.ts:50:6)
    at Layer.handle [as handle_request] (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/index.js:317:13)
    at /Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/gustavo/Documents/dev/code/personal/projects/saskiabot/server/node_modules/express/lib/router/index.js:275:10)```

**Comment by gsmgg** [comment]
If it help, my code:

```ts
import express from "express";

import { RateLimiterMongo } from "rate-limiter-flexible";
import MongoClient from "mongodb";

const app = express();

const mongoOpts = {
  useUnifiedTopology: true,
};

/**
 * I created this project in mongodb just to test this application,
 * so I put the username and password here in the code just
 * to make your testing simpler.
 *
 * THIS IS NOT A PRODUCTION BD and will be disabled in the future
 * when I manage to fix the problem.
 */

const db = {
  user: "test_admin",
  password: "Lc8vIC3WWXOBuMN9",
  dbname: "rate-limit",
};
const url = `mongodb+srv://${db.user}:${db.password}@testedb.bax1d.mongodb.net//test?retryWrites=true&w=majority&useNewUrlParser=true&useUnifiedTopology=true`;

const mongoConn = MongoClient.connect(url, mongoOpts);

const opts = {
  storeClient: mongoConn,
  dbName: "rate-limit",
  points: 10, // 10 points
  duration: 60, // 60 seconds
};
const rateLimiterMiddleware = (
  req: express.Request,
  res: express.Response,
  next: express.NextFunction
) => {
  const userId = req.query.uid as string;

  if (!userId) {
    res.status(401).send("Unauthorized");
    return;
  }

  const rateLimiterMongo = new RateLimiterMongo(opts);
  rateLimiterMongo
    .consume(userId, 2) // consume 2 points
    .then((rateLimiterRes) => {
      console.log(`User ${userId} do a request`);
      next();
    })
    .catch((rateLimiterRes) => {
      console.log("Error => ", rateLimiterRes);
      res.status(429).send("Too Many Requests");
    });
};

app.use(rateLimiterMiddleware);

app.get("/", (req: express.Request, res: express.Response) => {
  res.send(`Hi user ${req.params.uid}!`);
});

const port = 3000;
app.listen(port, () => {
  console.log(`Server listening at http://localhost:${port}`);
});

```

**Comment by animir** [comment]
@gsmgg Hi, this line `const rateLimiterMongo = new RateLimiterMongo(opts)` should be moved out of the middleware. Rate limiter instance should be created once.

**Comment by gsmgg** [comment]
That worked! My god, how did I not see this before?! 

Thank you so much for your help <3!!
