### ISSUE TITLE
express middleware filter out localhost api calls

### ISSUE THREAD

**Issue by loretoparisi** [animir/node-rate-limiter-flexible#14]
I'm running a Cluster/Worker configuration and I do internal api calls to `localhost`. Having configured the rate limiter as a express middleware, I get these internal api calls limited too:

```javascript
const rateLimiterMiddleware = (req, res, next) => {
                rateLimiter.consume(req.connection.remoteAddress)
                    .then(() => {
                        next();
                    })
                    .catch(_ => {
                        var errorMessage = APIHelper.createErrorMessage(429, '', '', 'Too Many Requests');
                        res.status(429).send(errorMessage);
                    });
            };
            self.app.use(rateLimiterMiddleware);
```

It would be possibile to filter out `localhost` / `127.0.0.1` IP address so that the middleware would skip these internal api calls?

**Comment by animir** [comment]
There is [Black-and-White list wrapper](https://github.com/animir/node-rate-limiter-flexible/wiki/Black-and-White-lists) for that

**Comment by loretoparisi** [comment]
@animir thank you. A question. In my specific case (whitelist `localhost`) I should do like

```javascript
const limiterWrapped = new RLWrapperBlackAndWhite({
      limiter,
      whiteList: ['127.0.0.1'],
      isWhite: (ip) => true,
      isBlack: (ip) => false,
      runActionAnyway: false,
    }); 
```
Correct?
Another question. Does the RLWrapperBlackAndWhite support masks in IP lists?
Thanks a lot!

**Comment by animir** [comment]
@loretoparisi `whiteList` is correct

`isBlack` or `isWhite` functions can be used to set mask. You don't need functions, if you can list white or black IPs
See example in [docs](https://github.com/animir/node-rate-limiter-flexible/wiki/Black-and-White-lists), I've improved docs by the way

**Comment by loretoparisi** [comment]
@animir got it, glad to help! closing...

**Comment by loretoparisi** [comment]
@animir sorry! Just to be sure when I add the wrapper to express is as usual?

```javascript
const rateLimiterMiddleware = (req, res, next) => {
                rateLimiter.consume(req.connection.remoteAddress)
                    .then(() => {
                        next();
                    })
                    .catch(_ => {
                        var errorMessage = APIHelper.createErrorMessage(429, '', '', 'Too Many Requests');
                        res.status(429).send(errorMessage);
                    });
            };
            const limiterWrapped = new RLWrapperBlackAndWhite({
                rateLimiterMiddleware,
                whiteList: ['127.0.0.1'],
                runActionAnyway: false,
              }); 
            self.app.use(rateLimiterMiddleware);
```

**Comment by loretoparisi** [comment]
@animir so I have corrected my code, it should be like

```javascript
const rateLimiterMemory = new RateLimiterMemory({
    points: 11,
    duration: 1,
    execEvenly: false
});
const limiterWrapped = new RLWrapperBlackAndWhite({
    rateLimiterMemory,
    whiteList: ['127.0.0.1'],
    runActionAnyway: false,
});
const rateLimiterMiddleware = (req, res, next) => {
    limiterWrapped.consume(req.connection.remoteAddress)
        .then(() => {
            next();
        })
        .catch(_ => {
            var errorMessage = APIHelper.createErrorMessage(429, '', '', 'Too Many Requests');
            res.status(429).send(errorMessage);
        });
};
self.app.use(rateLimiterMiddleware);
```

but I'm still missing the import of `RLWrapperBlackAndWhite`.

**Comment by animir** [comment]
@loretoparisi hi, config looks right

you're right, there was a bug with import

I've prepared a patch `v0.19.6`

**Comment by loretoparisi** [comment]
@animir I'm getting the error `limiter is not set` now.

```sh
Master 13128 error Error: limiter is not set
    at RLWrapperBlackAndWhite.set limiter [as limiter] (/node_modules/rate-limiter-flexible/lib/RLWrapperBlackAndWhite.js:19:13)
    at new RLWrapperBlackAndWhite (/node_modules/rate-limiter-flexible/lib/RLWrapperBlackAndWhite.js:5:18)
    at API.start (/lib/api.js:195:36)
    at self.platform.getNodeInfo.then.then.then.then.then._ (/
```

Any idea? My code is

```javascript
const rateLimiterMemory = new RateLimiterMemory({
    points: 11,
    duration: 1,
    execEvenly: false
});
const limiterWrapped = new RLWrapperBlackAndWhite({
    rateLimiterMemory,
    whiteList: ['127.0.0.1'],
    runActionAnyway: false,
});
const rateLimiterMiddleware = (req, res, next) => {
    limiterWrapped.consume(req.connection.remoteAddress)
        .then(() => {
            next();
        })
        .catch(_ => {
            var errorMessage = APIHelper.createErrorMessage(429, '', '', 'Too Many Requests');
            res.status(429).send(errorMessage);
        });
};
self.app.use(rateLimiterMiddleware);
```
