### ISSUE TITLE
[bug] RateLimiterMongodb cannot read property 'points' of null

### ISSUE THREAD

**Issue by robertsLando** [animir/node-rate-limiter-flexible#170]
Stack: 

```
TypeError: Cannot read property 'points' of null
              at RateLimiterMongo._getRateLimiterRes (node_modules/rate-limiter-flexible/lib/RateLimiterMongo.js:124:33)
              at RateLimiterMongo._afterConsume (node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:51:22)
              at node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:205:16
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This happens the first time `consume` is called and no docs are present in the related collection, this started happening when I switched to mongodb 4+ and mongoose 6.3.1

**Comment by animir** [comment]
@robertsLando Hey, with `mongoose` v6.x your app should wait until connection established before it can be used. More context in this closed issue https://github.com/animir/node-rate-limiter-flexible/issues/161

**Comment by robertsLando** [comment]
@animir Ok that worked, thanks
