### ISSUE TITLE
MongoServerError: The 'expireAfterSeconds' option is supported on '_ts' field only

### ISSUE THREAD

**Issue by sabhas** [animir/node-rate-limiter-flexible#206]
We get the following error when using Microsoft Azure's CosmosDB for MongoDB along with RateLimiterMongo:

```
MongoServerError: The 'expireAfterSeconds' option is supported on '_ts' field only.
    at Connection.onMessage (/snapshot/api/node_modules/mongodb/lib/cmap/connection.js:207:30)
    at MessageStream.<anonymous> (/snapshot/api/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:526:28)
    at processIncomingData (/snapshot/api/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/snapshot/api/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  code: 2,
  codeName: 'BadValue',
  [Symbol(errorLabels)]: Set(0) {}
}
```

**Comment by animir** [comment]
@sabhas Hi, I am not sure CosmosDB is supported. It may have some differences from MongoDB. Let us know, if you find a solution. Thanks.

**Comment by sabhas** [comment]
> @sabhas Hi, I am not sure CosmosDB is supported. It may have some differences from MongoDB. Let us know, if you find a solution. Thanks.

Currently, I used `RateLimiterMemory` instead of `RateLimiterMongo` as a workaround. But when I get some time I'll explore in more detail to find a better solution that should work with CosmosDB.

**Comment by animir** [comment]
Closing this for now. Feel free to re-open.
