### ISSUE TITLE
Rate limit redis - Express middleware

### ISSUE THREAD

**Issue by monstercoder0** [animir/node-rate-limiter-flexible#224]
TypeError: this.client.rlflxIncr is not a function
    at RateLimiterRedis._upsert (C:\Users\Redis\redis-demo\node_modules\rate-limiter-flexible\lib\RateLimiterRedis.js:107:28)
    at C:\Users\Redis\redis-demo\node_modules\rate-limiter-flexible\lib\RateLimiterStoreAbstract.js:203:12
    at new Promise (<anonymous>)
    at RateLimiterRedis.consume (C:\Users\Redis\redis-demo\node_modules\rate-limiter-flexible\lib\RateLimiterStoreAbstract.js:195:12)
    at rateLimiterMiddleware (C:\Users\Redis\redis-demo\middleware\rateLimiterRedis.js:33:17)
    at Layer.handle [as handle_request] (C:\Users\Redis\redis-demo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Redis\redis-demo\node_modules\express\lib\router\index.js:328:13)        
    at C:\Users\Redis\redis-demo\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\Redis\redis-demo\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\Redis\redis-demo\node_modules\express\lib\router\index.js:280:10)

**Comment by animir** [comment]
@monstercoder0 Hi, what version of `rate-limiter-flexible` do you use? What redis package and version?

**Comment by monstercoder0** [comment]
latest version

**Comment by monstercoder0** [comment]
"redis": "^4.6.10",
"rate-limiter-flexible": "^3.0.0"

**Comment by animir** [comment]
@monstercoder0 Ok, thanks.
Express middleware example is outdated.
You should add `useRedisPackage: true` like in this example https://github.com/animir/node-rate-limiter-flexible/wiki/Redis#redis-package

**Comment by monstercoder0** [comment]
As you said I add the following line `usePedisPackage: true` 

`ClientClosedError: The client is closed
    at Commander._RedisClient_sendCommand (C:\Users\Redis\redis-demo\node_modules\@redis\client\dist\lib\client\index.js:494:31)`
    
Honestly, This is frustrating me, so I create my own package.
