### ISSUE TITLE
MySQL databases with a dash in the name cause a ER_PARSE_ERROR failure

### ISSUE THREAD

**Issue by mattandrews** [animir/node-rate-limiter-flexible#36]
I use suffixes like `-dev`, `-test` etc for my databases. When I try to initialise this library with a `dbName` of `website-dev` etc I get this error:

```
{ Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for 
the right syntax to use near '-dev' at line 1
    at Packet.asError (/Users/matt/dev/myapp/node_modules/mysql2/lib/packets/packet.js:714:13)
    at Query.Command.execute (/Users/matt/dev/myapp/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/Users/matt/dev/myapp/node_modules/mysql2/lib/connection.js:513:28)
    at PacketParser.onPacket (/Users/matt/dev/myapp/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/Users/matt/dev/myapp/node_modules/mysql2/lib/packet_parser.js:76:14)
    at Socket.<anonymous> (/Users/matt/dev/myapp/node_modules/mysql2/lib/connection.js:89:29)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000'
}
```

I tried wrapping the database name in backticks which seemed to work (eg. it created the table in the `website-dev` database), but the middleware I created (from [here](https://github.com/animir/node-rate-limiter-flexible/wiki/Express-Middleware)) only returned failures (eg. the 429 error) and did not insert anything into the database.

**Comment by animir** [comment]
@mattandrews good catch. I've fixed and released `1.1.1`

**Comment by animir** [comment]
Closing this, be free to re-open if something pops up

**Comment by mattandrews** [comment]
Great, thank you for the quick fix!
