### ISSUE TITLE
Sequelize Error: Table is not created yet

### ISSUE THREAD

**Issue by pete183** [animir/node-rate-limiter-flexible#68]
I receive this error `Error: Table is not created yet` however it creates the table called `Limiters` fine.

```typescript
import { RateLimiterMySQL } from "rate-limiter-flexible";
import { Handler, Request } from "express";
import { db } from "../../models";
import { config } from "../../config/";

class RateLimiterMiddleware extends RateLimiterMySQL {
  constructor(ready) {
    super(
      {
        storeClient: db.sequelize,
        dbName: config.mysql.database,
        points: 10,
        duration: 1,
      },
      ready,
    );
  }
  middleware: Handler = async (request: Request, response, next) => {
    try {
      await this.consume(request.ip);
      next();
    } catch (error) {
      response.sendStatus(429); // Too Many Requests
    }
  };
}

export { RateLimiterMiddleware };
```

I can see that the table has been created
![image](https://user-images.githubusercontent.com/8902608/79106852-30af7800-7d6b-11ea-899f-4782de322804.png)

**Comment by animir** [comment]
@pete183 Hi. What is `ready` callback in your project? Do you wait response from it before running express app?

**Comment by pete183** [comment]
I give it this as the `ready` function:

```typescript
const createApp = async () => {
  await sync();

  const app = express();
  const ready = err => {
    if (err) {
      // log or/and process exit
    } else {
      // db and table checked/created
    }
  };

  app.use(new RateLimiterMiddleware(ready).middleware);

  const apolloServer = new ApolloServer({
    typeDefs,
    resolvers,
    context: ({ req }: { req: Request }) => ({
      ...jwtController.createAuthScope(req.headers.authorization),
    }),
  });
  apolloServer.applyMiddleware({
    app,
  });
  return app;
};
```

**Comment by pete183** [comment]
```
Error: Table is not created yet
    at RateLimiterMiddleware._upsert (/backend/node_modules/rate-limiter-flexible/lib/RateLimiterMySQL.js:281:29)
    at Promise (/backend/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:203:12)
    at new Promise (<anonymous>)
    at RateLimiterMiddleware.consume (/backend/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:195:12)
    at RateLimiterMiddleware.<anonymous> (/backend/middlewares/rateLimiter/index.ts:27:20)
    at Generator.next (<anonymous>)
    at /backend/.build/middlewares/rateLimiter/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/backend/.build/middlewares/rateLimiter/index.js:3:12)
    at RateLimiterMiddleware.middleware (/backend/middlewares/rateLimiter/index.ts:18:7)
    at Layer.handle [as handle_request] (/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/backend/node_modules/express/lib/router/index.js:317:13)
    at /backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/backend/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/backend/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/backend/node_modules/express/lib/router/index.js:317:13)
    at /backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/backend/node_modules/express/lib/router/index.js:275:10)
    at query (/backend/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/backend/node_modules/express/lib/router/index.js:317:13)
    at /backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/backend/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/backend/node_modules/express/lib/router/index.js:174:3)
    at Function.handle (/backend/node_modules/express/lib/application.js:174:10)
    at Server.app (/backend/node_modules/express/lib/express.js:39:9)
    at Server.emit (events.js:198:13)
    at Server.EventEmitter.emit (domain.js:448:20)
    at parserOnIncoming (_http_server.js:679:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

**Comment by animir** [comment]
@pete183 thanks for details
Looks like, your Apollo server starts, before related table created/checked.
Could you try to move everything to `ready` callback and put instead of `// db and table checked/created` comment?

**Comment by pete183** [comment]
This produced the same error unfortunately.

```typescript
const createApp = async () => {
  await sync();

  const app = express();
  const ready = err => {
    if (err) {
      // log or/and process exit
    } else {
      // db and table checked/created

      CreateRoutes(app);

      const apolloServer = new ApolloServer({
        typeDefs,
        resolvers,
        context: ({ req }: { req: Request }) => ({
          ...jwtController.createAuthScope(req.headers.authorization),
        }),
      });
      apolloServer.applyMiddleware({
        app,
      });
    }
  };

  app.use(new RateLimiterMiddleware(ready).middleware);
  return app;
};
```

**Comment by animir** [comment]
@pete183 almost right. you should return Promise from createApp function not `app` variable. That promise should wait until ApolloServer created.

**Comment by pete183** [comment]
So I return createApp as an await already. Please could you give an example of what you mean if that'd be okay?

```typescript
const app = await createApp();
const server = awsServerlessExpress.createServer(app);
return awsServerlessExpress.proxy(server, event, context, "PROMISE")
  .promise;
```

**Comment by animir** [comment]
@pete183 ok, Promise should be resolved only when table is created/checked

```
const createApp = async () => {
  await sync();

  const app = express();
  return new Promise((resolve, reject) => {
    const ready = err => {
      if (err) {
        reject(err)
      } else {
        // db and table checked/created

        CreateRoutes(app);

        const apolloServer = new ApolloServer({
          typeDefs,
          resolvers,
          context: ({ req }: { req: Request }) => ({
            ...jwtController.createAuthScope(req.headers.authorization),
          }),
        });
        apolloServer.applyMiddleware({
          app,
        });
        // !!! you should resolve only when everything is ready
        resolve(app);
      }
    };

    app.use(new RateLimiterMiddleware(ready).middleware);
  })
};
```

**Comment by pete183** [comment]
Ah I see - thank you so much for your help!
